import { useState, useEffect } from 'react';
import masDataRaw from '../mas.json';
import { parseQwenData } from './utils/qwenParser';
import type { TimelinePhase, MasData } from './types';
import { Timeline } from './components/Timeline';
import { Hero } from './components/Hero';
import { Sidebar } from './components/Sidebar';

import experimentsData from './data/experiments_index.json';

export interface ExperimentIndexItem {
    id: string;
    title: string;
    path: string;
    source?: string;
    audioPath?: string;
}

function App() {
  const [phases, setPhases] = useState<TimelinePhase[]>([]);
  const [metrics, setMetrics] = useState<any>(null);
  const [sidebarOpen, setSidebarOpen] = useState(true);
  const [selectedExperimentId, setSelectedExperimentId] = useState<string | null>(null);
  const [audioPath, setAudioPath] = useState<string | undefined>(undefined);

  // Load default on mount
  useEffect(() => {
    loadDefault();
  }, []);

  const resolveAudioPath = (expId: string) => {
      // Logic: Extract XXXX_XX-XX from ID "output_TIMESTAMP_ID_XXXX_XX-XX"
      // or similar. RegEx matches the trailing pattern: \d{4}_\d+-\d+$
      const match = expId.match(/(\d{4}_\d+-\d+)$/);
      if (match) {
          return `audio/${match[1]}.wav`;
      }
      return undefined;
  };

  const loadDefault = () => {
    if (experimentsData && experimentsData.length > 0) {
        // Load the first experiment (Qwen 0000)
        handleSelectExperiment(experimentsData[0]);
    } else {
        // Fallback to mas.json if no index
        try {
            const data = masDataRaw as unknown as MasData;
            const items = parseQwenData(data, 'qwen');
            setPhases(items);
            extractMetrics(data);
            setSelectedExperimentId(null);
        } catch(e) {
            console.error("Failed to load default data", e);
        }
    }
  };

  const handleSelectExperiment = async (exp: ExperimentIndexItem) => {
      setSelectedExperimentId(exp.id);
      const source = exp.source || 'qwen';
      const audio = resolveAudioPath(exp.id);
      setAudioPath(audio);

      try {
          const response = await fetch(exp.path);
          const jsonData = await response.json();
          const phases = parseQwenData(jsonData, source);
          setPhases(phases);
          extractMetrics(jsonData);

          if (window.innerWidth < 768) setSidebarOpen(false);
      } catch (error) {
          console.error("Failed to load experiment data:", error);
          alert("Failed to load experiment data. Check console.");
      }
  };

  const extractMetrics = (data: any) => {
      try {
        const base = typeof data.base_prompt === 'string' ? JSON.parse(data.base_prompt) : data.base_prompt;
        if (base && base.metrics) {
            setMetrics(base.metrics);
        } else {
            setMetrics(null);
        }
    } catch (e) {
        console.error(e);
        setMetrics(null);
    }
  };

  return (
    <div className="min-h-screen bg-background text-textMain font-sans selection:bg-accent/30 selection:text-white flex">
      <Sidebar
        isOpen={sidebarOpen}
        setIsOpen={setSidebarOpen}
        currentExperimentId={selectedExperimentId}
        onSelectExperiment={handleSelectExperiment}
      />

      <div className={`flex-1 transition-all duration-300 ${sidebarOpen ? 'md:ml-80' : ''}`}>
        <Hero
            title={selectedExperimentId ? "Experiment Visualization" : "Symphony of Agents"}
            metrics={metrics}
            audioPath={audioPath}
        />

        <main className="container mx-auto pb-20">
            <Timeline phases={phases} />
        </main>

        <footer className="text-center py-8 text-textMuted text-sm border-t border-white/5 bg-black/20">
            <p>Generated by Google Deepmind • Multi-Agent Studio • v1.0.1</p>
        </footer>
      </div>
    </div>
  );
}

export default App;
